#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Modeler.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlquilerCarros")]
	public partial class EntAlquilerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertALQUILER(ALQUILER instance);
    partial void UpdateALQUILER(ALQUILER instance);
    partial void DeleteALQUILER(ALQUILER instance);
    #endregion
		
		public EntAlquilerDataContext() : 
				base(global::Platform.Modeler.Properties.Settings.Default.AlquilerCarrosConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EntAlquilerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntAlquilerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntAlquilerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntAlquilerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ALQUILER> ALQUILER
		{
			get
			{
				return this.GetTable<ALQUILER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ALQUILER")]
	public partial class ALQUILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _FECHA_ALQUILER;
		
		private int _USUARIO_CEDULA;
		
		private string _VEHICULO_PLACA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFECHA_ALQUILERChanging(System.DateTime value);
    partial void OnFECHA_ALQUILERChanged();
    partial void OnUSUARIO_CEDULAChanging(int value);
    partial void OnUSUARIO_CEDULAChanged();
    partial void OnVEHICULO_PLACAChanging(string value);
    partial void OnVEHICULO_PLACAChanged();
    #endregion
		
		public ALQUILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ALQUILER", DbType="Date NOT NULL")]
		public System.DateTime FECHA_ALQUILER
		{
			get
			{
				return this._FECHA_ALQUILER;
			}
			set
			{
				if ((this._FECHA_ALQUILER != value))
				{
					this.OnFECHA_ALQUILERChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ALQUILER = value;
					this.SendPropertyChanged("FECHA_ALQUILER");
					this.OnFECHA_ALQUILERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CEDULA", DbType="Int NOT NULL")]
		public int USUARIO_CEDULA
		{
			get
			{
				return this._USUARIO_CEDULA;
			}
			set
			{
				if ((this._USUARIO_CEDULA != value))
				{
					this.OnUSUARIO_CEDULAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_CEDULA = value;
					this.SendPropertyChanged("USUARIO_CEDULA");
					this.OnUSUARIO_CEDULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEHICULO_PLACA", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string VEHICULO_PLACA
		{
			get
			{
				return this._VEHICULO_PLACA;
			}
			set
			{
				if ((this._VEHICULO_PLACA != value))
				{
					this.OnVEHICULO_PLACAChanging(value);
					this.SendPropertyChanging();
					this._VEHICULO_PLACA = value;
					this.SendPropertyChanged("VEHICULO_PLACA");
					this.OnVEHICULO_PLACAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
