<?xml version="1.0" encoding="utf-8"?><Database Name="Servicio" Class="EntAlquilerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SANTYID;Initial Catalog=Servicio;Persist Security Info=True;User ID=sa" SettingsObjectName="Platform.Modeler.Properties.Settings" SettingsPropertyName="ServicioConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ALQUILER" Member="ALQUILER">
    <Type Name="ALQUILER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FECHA_ALQUILER" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="USUARIO_CEDULA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VEHICULO_PLACA" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>