<?xml version="1.0" encoding="utf-8"?><Database Name="AlquilerCarros" Class="EntGeneroDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SANTYID;Initial Catalog=AlquilerCarros;User ID=sa" SettingsObjectName="Platform.Modeler.Properties.Settings" SettingsPropertyName="AlquilerCarrosConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GENERO" Member="GENERO">
    <Type Name="GENERO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>