#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Modeler.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Servicio")]
	public partial class EntUsuarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    #endregion
		
		public EntUsuarioDataContext() : 
				base(global::Platform.Modeler.Properties.Settings.Default.ServicioConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntUsuarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntUsuarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntUsuarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntUsuarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CEDULA;
		
		private string _NOMBRE;
		
		private string _APELLIDO;
		
		private System.Nullable<int> _EDAD;
		
		private int _GENERO_ID;
		
		private int _TIPO_DOCUMENTO_ID;
		
		private int _CIUDAD_ID;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCEDULAChanging(int value);
    partial void OnCEDULAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDOChanging(string value);
    partial void OnAPELLIDOChanged();
    partial void OnEDADChanging(System.Nullable<int> value);
    partial void OnEDADChanged();
    partial void OnGENERO_IDChanging(int value);
    partial void OnGENERO_IDChanged();
    partial void OnTIPO_DOCUMENTO_IDChanging(int value);
    partial void OnTIPO_DOCUMENTO_IDChanged();
    partial void OnCIUDAD_IDChanging(int value);
    partial void OnCIUDAD_IDChanged();
    #endregion
		
		public USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CEDULA
		{
			get
			{
				return this._CEDULA;
			}
			set
			{
				if ((this._CEDULA != value))
				{
					this.OnCEDULAChanging(value);
					this.SendPropertyChanging();
					this._CEDULA = value;
					this.SendPropertyChanged("CEDULA");
					this.OnCEDULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(25)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="NVarChar(25)")]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this.OnAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO = value;
					this.SendPropertyChanged("APELLIDO");
					this.OnAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDAD", DbType="Int")]
		public System.Nullable<int> EDAD
		{
			get
			{
				return this._EDAD;
			}
			set
			{
				if ((this._EDAD != value))
				{
					this.OnEDADChanging(value);
					this.SendPropertyChanging();
					this._EDAD = value;
					this.SendPropertyChanged("EDAD");
					this.OnEDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENERO_ID", DbType="Int NOT NULL")]
		public int GENERO_ID
		{
			get
			{
				return this._GENERO_ID;
			}
			set
			{
				if ((this._GENERO_ID != value))
				{
					this.OnGENERO_IDChanging(value);
					this.SendPropertyChanging();
					this._GENERO_ID = value;
					this.SendPropertyChanged("GENERO_ID");
					this.OnGENERO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DOCUMENTO_ID", DbType="Int NOT NULL")]
		public int TIPO_DOCUMENTO_ID
		{
			get
			{
				return this._TIPO_DOCUMENTO_ID;
			}
			set
			{
				if ((this._TIPO_DOCUMENTO_ID != value))
				{
					this.OnTIPO_DOCUMENTO_IDChanging(value);
					this.SendPropertyChanging();
					this._TIPO_DOCUMENTO_ID = value;
					this.SendPropertyChanged("TIPO_DOCUMENTO_ID");
					this.OnTIPO_DOCUMENTO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD_ID", DbType="Int NOT NULL")]
		public int CIUDAD_ID
		{
			get
			{
				return this._CIUDAD_ID;
			}
			set
			{
				if ((this._CIUDAD_ID != value))
				{
					this.OnCIUDAD_IDChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD_ID = value;
					this.SendPropertyChanged("CIUDAD_ID");
					this.OnCIUDAD_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
