#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Modeler.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlquilerCarros")]
	public partial class EntVehiculoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertVEHICULO(VEHICULO instance);
    partial void UpdateVEHICULO(VEHICULO instance);
    partial void DeleteVEHICULO(VEHICULO instance);
    #endregion
		
		public EntVehiculoDataContext() : 
				base(global::Platform.Modeler.Properties.Settings.Default.AlquilerCarrosConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EntVehiculoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntVehiculoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntVehiculoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntVehiculoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VEHICULO> VEHICULO
		{
			get
			{
				return this.GetTable<VEHICULO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VEHICULO")]
	public partial class VEHICULO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PLACA;
		
		private string _NPUERTAS;
		
		private string _COLOR;
		
		private string _VALORDIA;
		
		private int _MARCA_ID;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPLACAChanging(string value);
    partial void OnPLACAChanged();
    partial void OnNPUERTASChanging(string value);
    partial void OnNPUERTASChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnVALORDIAChanging(string value);
    partial void OnVALORDIAChanged();
    partial void OnMARCA_IDChanging(int value);
    partial void OnMARCA_IDChanged();
    #endregion
		
		public VEHICULO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLACA", DbType="NVarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PLACA
		{
			get
			{
				return this._PLACA;
			}
			set
			{
				if ((this._PLACA != value))
				{
					this.OnPLACAChanging(value);
					this.SendPropertyChanging();
					this._PLACA = value;
					this.SendPropertyChanged("PLACA");
					this.OnPLACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPUERTAS", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string NPUERTAS
		{
			get
			{
				return this._NPUERTAS;
			}
			set
			{
				if ((this._NPUERTAS != value))
				{
					this.OnNPUERTASChanging(value);
					this.SendPropertyChanging();
					this._NPUERTAS = value;
					this.SendPropertyChanged("NPUERTAS");
					this.OnNPUERTASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALORDIA", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string VALORDIA
		{
			get
			{
				return this._VALORDIA;
			}
			set
			{
				if ((this._VALORDIA != value))
				{
					this.OnVALORDIAChanging(value);
					this.SendPropertyChanging();
					this._VALORDIA = value;
					this.SendPropertyChanged("VALORDIA");
					this.OnVALORDIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARCA_ID", DbType="Int NOT NULL")]
		public int MARCA_ID
		{
			get
			{
				return this._MARCA_ID;
			}
			set
			{
				if ((this._MARCA_ID != value))
				{
					this.OnMARCA_IDChanging(value);
					this.SendPropertyChanging();
					this._MARCA_ID = value;
					this.SendPropertyChanged("MARCA_ID");
					this.OnMARCA_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
